-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.app_info
(
    app_id serial NOT NULL,
    app_name character varying(255) COLLATE pg_catalog."default",
    app_img text COLLATE pg_catalog."default",
    app_name_company character varying(255) COLLATE pg_catalog."default",
    app_version character varying(100) COLLATE pg_catalog."default",
    app_total_rate character varying(50) COLLATE pg_catalog."default",
    app_average_rate character varying(50) COLLATE pg_catalog."default",
    app_install character varying(50) COLLATE pg_catalog."default",
    app_category character varying(200) COLLATE pg_catalog."default",
    app_size character varying(50) COLLATE pg_catalog."default",
    app_last_update text COLLATE pg_catalog."default",
    app_url text COLLATE pg_catalog."default",
    app_img_base64 text COLLATE pg_catalog."default",
    CONSTRAINT apps_pkey PRIMARY KEY (app_id),
    CONSTRAINT app_info_app_name_key UNIQUE (app_name)
);

CREATE TABLE IF NOT EXISTS public.comment
(
    comment_id serial NOT NULL,
    app_id integer,
    user_name character varying(255) COLLATE pg_catalog."default",
    comment_text text COLLATE pg_catalog."default",
    comment_rating numeric(2, 1),
    comment_date date,
    sentiment_result character varying(255) COLLATE pg_catalog."default",
    sentiment_processed boolean,
    iid text COLLATE pg_catalog."default",
    comment_idd integer,
    CONSTRAINT comment_pkey PRIMARY KEY (comment_id),
    CONSTRAINT unique_comment_idd UNIQUE (comment_idd)
);

CREATE TABLE IF NOT EXISTS public.processing_logs
(
    log_id serial NOT NULL,
    comment_id integer,
    model_id integer,
    sentiment character varying(255) COLLATE pg_catalog."default",
    processing_date timestamp with time zone,
    status character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT processing_logs_pkey PRIMARY KEY (log_id)
);

CREATE TABLE IF NOT EXISTS public.sentiment_model
(
    model_id serial NOT NULL,
    model_name character varying(255) COLLATE pg_catalog."default",
    model_version character varying(50) COLLATE pg_catalog."default",
    last_update date,
    CONSTRAINT sentiment_model_pkey PRIMARY KEY (model_id)
);

CREATE TABLE IF NOT EXISTS public.stop_words
(
    stopword_id serial NOT NULL,
    app_id integer,
    stopword text COLLATE pg_catalog."default",
    CONSTRAINT stop_words_pkey PRIMARY KEY (stopword_id)
);

CREATE TABLE IF NOT EXISTS public.url_to_crawl
(
    crawl_app_id serial NOT NULL,
    crawl_app_name character varying(255) COLLATE pg_catalog."default",
    crawl_url text COLLATE pg_catalog."default",
    CONSTRAINT url_to_crawl_pkey PRIMARY KEY (crawl_app_id)
);

ALTER TABLE IF EXISTS public.comment
    ADD CONSTRAINT comment_app_id_fkey FOREIGN KEY (app_id)
    REFERENCES public.app_info (app_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.processing_logs
    ADD CONSTRAINT processing_logs_comment_id_fkey FOREIGN KEY (comment_id)
    REFERENCES public.comment (comment_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.processing_logs
    ADD CONSTRAINT processing_logs_model_id_fkey FOREIGN KEY (model_id)
    REFERENCES public.sentiment_model (model_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.stop_words
    ADD CONSTRAINT stop_words_app_id_fkey FOREIGN KEY (app_id)
    REFERENCES public.app_info (app_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;




-- Initial URL entry
INSERT INTO public.url_to_crawl (crawl_app_name, crawl_url) VALUES
('HamrahBankMellat', 'https://cafebazaar.ir/app/com.pmb.mobile?l=fa'),
('MegaBank', 'https://cafebazaar.ir/app/com.bpm.social?l=fa'),
('‌Bale', 'https://cafebazaar.ir/app/ir.nasim?l=fa'),
('BluBank', 'https://cafebazaar.ir/app/com.samanpr.blu?l=fa'),
('Wepod', 'https://cafebazaar.ir/app/com.dotin.wepod?l=fa'),
('Bankino', 'https://cafebazaar.ir/app/digital.neobank?l=fa'),
('Bam', 'https://cafebazaar.ir/app/ir.bmi.bam.nativeweb?l=fa'),
('Mehr', 'https://cafebazaar.ir/app/com.ada.mbank.mehr?l=fa'),
('Shahr', 'https://cafebazaar.ir/app/com.citydi.hplus?l=fa'),
('Parsian', 'https://cafebazaar.ir/app/com.parsmobapp?l=fa'),
('Day', 'https://cafebazaar.ir/app/com.tosan.dara.day?l=fa'),
('Saman', 'https://cafebazaar.ir/app/ir.mobillet.app?l=fa'),
('Baran', 'https://cafebazaar.ir/app/com.gostaresh.mobilebank.boilerplate?l=fa'),
('Abanak', 'https://cafebazaar.ir/app/com.abankefarda?l=fa'),

('HamrahKart', 'https://cafebazaar.ir/app/com.adpdigital.mbs.ayande?l=fa'),
('HiBank', 'https://cafebazaar.ir/app/ir.karafarinbank.digital.mb?l=fa'),
('Banlet', 'https://cafebazaar.ir/app/com.ada.mbank.bankette?l=fa'),
('RefahMobileBank', 'https://cafebazaar.ir/app/com.refahbank.dpi.android?l=fa'),
('SepahHamrahBank', 'https://cafebazaar.ir/app/mob.banking.android.sepah?l=fa'),
('Resalt', 'https://cafebazaar.ir/app/mob.banking.android.resalat?l=fa'),
('Pasargad', 'https://cafebazaar.ir/app/mob.banking.android.pasargad?l=fa'),
('SaderatHamrahBank', 'https://cafebazaar.ir/app/com.isc.bsinew?l=fa'),
('TejaratHamrahBank', 'https://cafebazaar.ir/app/ir.tejaratbank.tata.mobile.android.tejarat?l=fa'),
('KeshavarziHamrahBank', 'https://cafebazaar.ir/app/com.bki.mobilebanking.android?l=fa'),
('PostBank', 'https://cafebazaar.ir/app/com.tosan.dara.postbank?l=fa'),
('Taavon', 'https://cafebazaar.ir/app/mob.banking.android.taavon?l=fa'),
('HamrahNovin', 'https://cafebazaar.ir/app/com.farazpardazan.enbank?l=fa'),
('Sarmayeh', 'https://cafebazaar.ir/app/ir.tes.sarmayeh?l=fa') ,
('QBank', 'https://cafebazaar.ir/app/com.rahand.qbank'),
('Sina', 'https://cafebazaar.ir/app/com.hafizco.mobilebanksina'),
('‌Melal', 'https://cafebazaar.ir/app/com.melal')
;



END;