-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.app_info
(
    app_id serial NOT NULL,
    app_name character varying(255) COLLATE pg_catalog."default",
    app_img text COLLATE pg_catalog."default",
    app_name_company character varying(255) COLLATE pg_catalog."default",
    app_version character varying(100) COLLATE pg_catalog."default",
    app_total_rate character varying(50) COLLATE pg_catalog."default",
    app_average_rate character varying(50) COLLATE pg_catalog."default",
    app_install character varying(50) COLLATE pg_catalog."default",
    app_category character varying(200) COLLATE pg_catalog."default",
    app_size character varying(50) COLLATE pg_catalog."default",
    app_last_update text COLLATE pg_catalog."default",
    app_url text COLLATE pg_catalog."default",
    app_img_base64 text COLLATE pg_catalog."default",
    CONSTRAINT apps_pkey PRIMARY KEY (app_id),
    CONSTRAINT app_info_app_name_key UNIQUE (app_name)
);

CREATE TABLE IF NOT EXISTS public.comment
(
    comment_id serial NOT NULL,
    app_id integer,
    user_name character varying(255) COLLATE pg_catalog."default",
    comment_text text COLLATE pg_catalog."default",
    comment_rating numeric(2, 1),
    comment_date date,
    sentiment_result character varying(255) COLLATE pg_catalog."default",
    sentiment_processed boolean,
    iid text COLLATE pg_catalog."default",
    comment_idd integer,
    CONSTRAINT comment_pkey PRIMARY KEY (comment_id),
    CONSTRAINT unique_comment_idd UNIQUE (comment_idd)
);

CREATE TABLE IF NOT EXISTS public.log_app
(
    log_app_id serial NOT NULL,
    app_id integer NOT NULL,
    app_name character varying(255) COLLATE pg_catalog."default",
    app_name_company character varying(255) COLLATE pg_catalog."default",
    app_version character varying(100) COLLATE pg_catalog."default",
    app_total_rate character varying(50) COLLATE pg_catalog."default",
    app_average_rate character varying(50) COLLATE pg_catalog."default",
    app_install character varying(50) COLLATE pg_catalog."default",
    app_category character varying(200) COLLATE pg_catalog."default",
    app_size character varying(50) COLLATE pg_catalog."default",
    app_last_update text COLLATE pg_catalog."default",
    app_scraped_time timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    app_img text COLLATE pg_catalog."default",
    CONSTRAINT log_app_pkey PRIMARY KEY (log_app_id)
);

CREATE TABLE IF NOT EXISTS public.processing_logs
(
    log_id serial NOT NULL,
    comment_id integer,
    model_id integer,
    sentiment character varying(255) COLLATE pg_catalog."default",
    processing_date timestamp with time zone,
    status character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT processing_logs_pkey PRIMARY KEY (log_id)
);

CREATE TABLE IF NOT EXISTS public.sentiment_model
(
    model_id serial NOT NULL,
    model_name character varying(255) COLLATE pg_catalog."default",
    model_version character varying(50) COLLATE pg_catalog."default",
    last_update date,
    CONSTRAINT sentiment_model_pkey PRIMARY KEY (model_id)
);

CREATE TABLE IF NOT EXISTS public.stop_words
(
    stopword_id serial NOT NULL,
    app_id integer,
    stopword text COLLATE pg_catalog."default",
    CONSTRAINT stop_words_pkey PRIMARY KEY (stopword_id)
);

CREATE TABLE IF NOT EXISTS public.url_to_crawl
(
    crawl_app_id serial NOT NULL,
    crawl_app_name character varying(255) COLLATE pg_catalog."default",
    crawl_url text COLLATE pg_catalog."default",
    CONSTRAINT url_to_crawl_pkey PRIMARY KEY (crawl_app_id)
);

ALTER TABLE IF EXISTS public.comment
    ADD CONSTRAINT comment_app_id_fkey FOREIGN KEY (app_id)
    REFERENCES public.app_info (app_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.log_app
    ADD CONSTRAINT log_app_app_id_fkey FOREIGN KEY (app_id)
    REFERENCES public.app_info (app_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.processing_logs
    ADD CONSTRAINT processing_logs_comment_id_fkey FOREIGN KEY (comment_id)
    REFERENCES public.comment (comment_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.processing_logs
    ADD CONSTRAINT processing_logs_model_id_fkey FOREIGN KEY (model_id)
    REFERENCES public.sentiment_model (model_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.stop_words
    ADD CONSTRAINT stop_words_app_id_fkey FOREIGN KEY (app_id)
    REFERENCES public.app_info (app_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;